### ISSUE TITLE
Time Varying Linear Quadratic control (Support)

### ISSUE THREAD

**Issue by mishapadidar** [JonasKoenemann/optimal-control#129]
I'm trying to solve a Linear Quadratic optimal control problem with time varying matrices. 

Question 1:
Is there a way to pass a time variable into the  differential equation handler so I can construct these _time-varying_ matrices? For example my differential equation might be
`
dx/dt = A(t)*x + B(t)*u
`
where the matrices A(t), B(t) are
`
A(t) = [t 0 ; 0 t^2]

B(t) = [1 0; 0 2*t]
`

Question 2:
Is there a way to write the differential equations and costs in matrix form? So far I have been writing out the differential equations one by one as in the following
` daeh.setODE('x1', u.u1*cos(x.x3));
  daeh.setODE('x2', u.u1*sin(x.x3));
`

**Comment by jkoendev** [comment]
Hi, sorry for the late reply!

q1: 
you can add a state for the time, e.g. as in the cartpole example:
```varh.addState('time', 'lb', 0, 'ub', 10);```
and differential equation:
```daeh.setODE('time', 1)```
[cartpole.m](https://github.com/OpenOCL/OpenOCL/blob/v5.08/%2Bocl/%2Bexamples/cartpole.m)

and use the `time` variable in our A and B matrix:
```
t = x.time;
A = [t 0 ; 0 t^2]
B = [1 0; 0 2*t]
```

q2:
you can add a matrix or vector valued variable (specify the size as second argument), e.g.
```varh.addState('x', [2,1])```
and differential equation in matrix form
```daeh.setODE('x', A*x+B*u)```

There is an example in the current `dev_acados` branch:
[mass_spring](https://github.com/OpenOCL/OpenOCL/tree/e571226f201a5faee2a9454db9a15c761bbde77e/%2Bocl/%2Bexamples/%2Bmass_spring)

**Comment by jkoendev** [comment]
for the time you probably also need to set a bound on the initial time:
```
solver.setInitialBounds('time', 0);
```

**Comment by mishapadidar** [comment]
Thanks for the support very helpful.
