### ISSUE TITLE
Version 7 - 'userdata' is not a recognized parameter

### ISSUE THREAD

**Issue by OrezRan** [JonasKoenemann/optimal-control#150]
I just downloaded the new version (7.03). For some reason, none of my codes (nor the examples) run - they all give the same error: 'userdata' is not a recognized parameter. Any ideas?

**Comment by jkoendev** [comment]
Thanks for the feedback!

have you got a previous version still in your path?

I suspect that there is a previous version of OpenOCL still installed or in your path. For version 7 i am not providing the .mltbx package anymore. 

If you have installed OpenOCL as a .mltbx toolbox before you probably need to remove it in:
Home -> Add-Ons -> Manage Add-Ons

**Comment by OrezRan** [comment]
Yep - this is indeed the problem. 
Many thanks!
O.
